name: master
on:
  push:
    branches:
    - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: docker://l.gcr.io/google/bazel:2.1.0
    steps:
    - uses: actions/checkout@v1
    - name: Buildifier
      run: bazel run @com_github_bazelbuild_buildtools//:buildifier
    - name: Gazelle
      run: bazel run //:gazelle
    - name: Gofmt
      run: bazel run @go_sdk//:bin/gofmt -- -s -w .
    - name: Clang format
      run: find . -name '*.proto' -exec bazel run @llvm_toolchain//:bin/clang-format -- -i {} +
    - name: Test style conformance
      run: git diff --exit-code HEAD --
    - name: Check for ineffective assignments
      run: bazel run @com_github_gordonklaus_ineffassign//:ineffassign $(pwd)
    - name: Bazel build and test
      run: bazel test //...

    - name: Install Docker credentials
      run: mkdir ~/.docker && echo "${DOCKER_CONFIG_JSON}" > ~/.docker/config.json
      env:
        DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON }}
    - name: Push container bb-runner-ubuntu16-04
      run: bazel run //cmd/bb_runner:bb_runner_ubuntu16_04_container_push
    - name: Push container bb-scheduler
      run: bazel run //cmd/bb_scheduler:bb_scheduler_container_push
    - name: Push container bb-worker
      run: bazel run //cmd/bb_worker:bb_worker_container_push
