name: master
on:
  push:
    branches:
    - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: docker://l.gcr.io/google/bazel:2.1.0
    steps:
    - name: Check out source code
      uses: actions/checkout@v1

    - name: Buildifier
      run: bazel run @com_github_bazelbuild_buildtools//:buildifier
    - name: Gazelle
      run: bazel run //:gazelle
    - name: Gofmt
      run: bazel run @go_sdk//:bin/gofmt -- -s -w .
    - name: Clang format
      run: find . -name '*.proto' -exec bazel run @llvm_toolchain//:bin/clang-format -- -i {} +
    - name: Test style conformance
      run: git diff --exit-code HEAD --
    - name: Golint
      run: bazel run @org_golang_x_lint//golint -- -set_exit_status $(pwd)/...
    - name: Check for ineffective assignments
      run: bazel run @com_github_gordonklaus_ineffassign//:ineffassign $(pwd)

    - name: Linux build and test
      run: bazel test --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //...
    - name: Upload bb_runner for Linux
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_runner.linux_amd64
        path: bazel-bin/cmd/bb_runner/linux_amd64_pure_stripped/bb_runner
    - name: Upload bb_scheduler for Linux
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_scheduler.linux_amd64
        path: bazel-bin/cmd/bb_scheduler/linux_amd64_pure_stripped/bb_scheduler
    - name: Upload bb_worker for Linux
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_worker.linux_amd64
        path: bazel-bin/cmd/bb_worker/linux_amd64_pure_stripped/bb_worker

    - name: macOS build
      run: bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //...
    - name: Upload bb_runner for macOS
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_runner.darwin_amd64
        path: bazel-bin/cmd/bb_runner/darwin_amd64_pure_stripped/bb_runner
    - name: Upload bb_scheduler for macOS
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_scheduler.darwin_amd64
        path: bazel-bin/cmd/bb_scheduler/darwin_amd64_pure_stripped/bb_scheduler
    - name: Upload bb_worker for macOS
      uses: actions/upload-artifact@v2-preview
      with:
        name: bb_worker.darwin_amd64
        path: bazel-bin/cmd/bb_worker/darwin_amd64_pure_stripped/bb_worker

    - name: Install Docker credentials
      run: mkdir ~/.docker && echo "${DOCKER_CONFIG_JSON}" > ~/.docker/config.json
      env:
        DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON }}
    - name: Push container bb-runner-ubuntu16-04
      run: bazel run //cmd/bb_runner:bb_runner_ubuntu16_04_container_push
    - name: Push container bb-runner-installer
      run: bazel run //cmd/bb_runner:bb_runner_installer_push
    - name: Push container bb-scheduler
      run: bazel run //cmd/bb_scheduler:bb_scheduler_container_push
    - name: Push container bb-worker
      run: bazel run //cmd/bb_worker:bb_worker_container_push
